[[main]]
  identifier = "規則"
  name = "遊戲規則"
  url = "docs"
  weight = 1

[[main]]
  identifier = "資料"
  name = "資料一覽"
  url = "data"
  weight = 2

[[main]]
  identifier = "角色卡"
  name = "線上角色卡"
  url = "https://docs.google.com/spreadsheets/d/1IQGBW50eJtib8fq7IgLVlzFxzwfhNs-5cpjy0WOu9XI/edit#gid=0"
  weight = 3

